// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  artice_listing: dynamic(() => import("./ArticeListing")),
  contact_form: dynamic(() => import("./ContactForm")),
  image_block: dynamic(() => import("./ImageBlock")),
  paragraph: dynamic(() => import("./Paragraph")),
  title_block: dynamic(() => import("./TitleBlock")),
};
