
import './globals.css';
import "@/assets/styles/index.scss";
import { Inter } from '@next/font/google';
import { Metadata } from 'next';
import Header from '@/components/shared/Header';
import Footer from '@/components/shared/Footer';

import type { ReactChildrenNode } from '@/types';

const inter = Inter({ subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


function RootLayout({ children }: ReactChildrenNode): JSX.Element {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}

export default RootLayout;