import './globals.css';
import { Inter } from 'next/font/google';
import { Metadata } from 'next';

import type { ReactChildrenNode } from '@/types';

const inter = Inter({ subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function RootLayout({ children }: ReactChildrenNode): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>{children}</main>
      </body>
    </html>
  )
}

export default RootLayout;